// Package digitwin with the agent request handler for using service 'ThingDirectory'
// This builds a service consumer that send a service request.
// DO NOT EDIT. This file is auto generated by tm2go. Any changes will be overwritten.
// Generated 18 Nov 2025 13:58 PST.
package digitwin

import "github.com/hiveot/hub/lib/consumer"

// ThingDirectoryCreateThing client method - Create Thing TD.
// Update the Thing TD in the directory. For use by Thing agents only.
func ThingDirectoryCreateThing(hc *consumer.Consumer, tDJSON string) (err error) {

	err = hc.Rpc("invokeaction", ThingDirectoryDThingID, ThingDirectoryCreateThingMethod, &tDJSON, nil)
	return
}

// ThingDirectoryDeleteThing client method - Delete Thing.
// Remove a digital twin TD from the directory
func ThingDirectoryDeleteThing(hc *consumer.Consumer, dThingID string) (err error) {

	err = hc.Rpc("invokeaction", ThingDirectoryDThingID, ThingDirectoryDeleteThingMethod, &dThingID, nil)
	return
}

// ThingDirectoryRetrieveAllThings client method - Read all TDs.
// Read a batch of TD documents
func ThingDirectoryRetrieveAllThings(hc *consumer.Consumer, limit int64, offset int64) (tDlist []string, err error) {
	var args = ThingDirectoryRetrieveAllThingsArgs{limit, offset}
	err = hc.Rpc("invokeaction", ThingDirectoryDThingID, ThingDirectoryRetrieveAllThingsMethod, &args, &tDlist)
	return
}

// ThingDirectoryRetrieveThing client method - Retrieve a TD.
// Return a JSON encoded TD document
func ThingDirectoryRetrieveThing(hc *consumer.Consumer, thingID string) (tD string, err error) {

	err = hc.Rpc("invokeaction", ThingDirectoryDThingID, ThingDirectoryRetrieveThingMethod, &thingID, &tD)
	return
}

// ThingDirectoryUpdateThing client method - Update Thing TD.
// Update the Thing TD in the directory. For use by agents only.
func ThingDirectoryUpdateThing(hc *consumer.Consumer, tD string) (err error) {

	err = hc.Rpc("invokeaction", ThingDirectoryDThingID, ThingDirectoryUpdateThingMethod, &tD, nil)
	return
}
