// Package digitwin with the agent request handler for using service 'ThingDirectory'
// This builds a service consumer that send a service request.
// DO NOT EDIT. This file is auto generated by td2go. Any changes will be overwritten.
// Generated 22 Feb 2025 12:16 PST. 
package digitwin

import "github.com/hiveot/hub/messaging"


// ThingDirectoryReadAllTDs client method - Read all TDs.
// Read a batch of TD documents
func ThingDirectoryReadAllTDs(hc *messaging.Consumer, limit int, offset int)(tDlist []string, err error){
    var args = ThingDirectoryReadAllTDsArgs{limit, offset}
    err = hc.Rpc("invokeaction", ThingDirectoryDThingID, ThingDirectoryReadAllTDsMethod, &args, &tDlist)
    return
}

// ThingDirectoryReadTD client method - Read TD.
// Return a JSON encoded TD document
func ThingDirectoryReadTD(hc *messaging.Consumer, thingID string)(tD string, err error){
    
    err = hc.Rpc("invokeaction", ThingDirectoryDThingID, ThingDirectoryReadTDMethod, &thingID, &tD)
    return
}

// ThingDirectoryRemoveTD client method - Remove TD.
// Remove a digital twin from the directory
func ThingDirectoryRemoveTD(hc *messaging.Consumer, dThingID string)(err error){
    
    err = hc.Rpc("invokeaction", ThingDirectoryDThingID, ThingDirectoryRemoveTDMethod, &dThingID, nil)
    return
}

// ThingDirectoryUpdateTD client method - Update TD.
// Update the Thing TD in the directory. For use by agents only.
func ThingDirectoryUpdateTD(hc *messaging.Consumer, tD string)(err error){
    
    err = hc.Rpc("invokeaction", ThingDirectoryDThingID, ThingDirectoryUpdateTDMethod, &tD, nil)
    return
}
