// Package digitwin with the agent request handler for using service 'ThingValues'
// This builds a service consumer that send a service request.
// DO NOT EDIT. This file is auto generated by td2go. Any changes will be overwritten.
// Generated 01 Feb 2025 10:23 PST.
package digitwin

import (
	"github.com/hiveot/hub/messaging/consumer"
)

// ThingValuesQueryAction client method - Action status.
// Read the current action status of a Thing
func ThingValuesQueryAction(hc *consumer.Consumer, name string, thingID string) (actionvalue ActionStatus, err error) {
	var args = ThingValuesQueryActionArgs{name, thingID}
	err = hc.Rpc("invokeaction", ThingValuesDThingID, ThingValuesQueryActionMethod, &args, &actionvalue)
	return
}

// ThingValuesQueryAllActions client method - Action statuses.
// Read all action statuses of a Thing
func ThingValuesQueryAllActions(hc *consumer.Consumer, thingID string) (actionvalue map[string]ActionStatus, err error) {

	err = hc.Rpc("invokeaction", ThingValuesDThingID, ThingValuesQueryAllActionsMethod, &thingID, &actionvalue)
	return
}

// ThingValuesReadAllEvents client method - Read all event values.
// Read the latest known event values of a Thing
func ThingValuesReadAllEvents(hc *consumer.Consumer, thingID string) (eventvalues map[string]ThingValue, err error) {

	err = hc.Rpc("invokeaction", ThingValuesDThingID, ThingValuesReadAllEventsMethod, &thingID, &eventvalues)
	return
}

// ThingValuesReadAllProperties client method - Read all properties.
// Read the latest known property values
func ThingValuesReadAllProperties(hc *consumer.Consumer, thingID string) (propertyvalues map[string]ThingValue, err error) {

	err = hc.Rpc("invokeaction", ThingValuesDThingID, ThingValuesReadAllPropertiesMethod, &thingID, &propertyvalues)
	return
}

// ThingValuesReadEvent client method - Read event value.
// Read the latest event value of a Thing
func ThingValuesReadEvent(hc *consumer.Consumer, name string, thingID string) (eventvalue ThingValue, err error) {
	var args = ThingValuesReadEventArgs{name, thingID}
	err = hc.Rpc("invokeaction", ThingValuesDThingID, ThingValuesReadEventMethod, &args, &eventvalue)
	return
}

// ThingValuesReadProperty client method - Read property value.
// Read the latest property value
func ThingValuesReadProperty(hc *consumer.Consumer, name string, thingID string) (propertyvalue ThingValue, err error) {
	var args = ThingValuesReadPropertyArgs{name, thingID}
	err = hc.Rpc("invokeaction", ThingValuesDThingID, ThingValuesReadPropertyMethod, &args, &propertyvalue)
	return
}
