# hub.yaml contains the hiveot hub core configuration


# Messaging server configuration
server:
  # specific listening address, default is 127.0.0.1
  # the host name or IP must match that of the certificate for TLS to work
  #host: "127.0.0.1"

  # default listening TLS port is 4222 and 4223 for websocket
  #port: 4222
  #wsPort: 8222

  # logging level for server: debug, info, warn (default), error
  #logLevel: "warn"
  # logfile to write to in the logging folder. Default is stderr
  #logFile: "hubcore.log"

  # maximum in-memory RAM usage. Default (0) is 100MB. -1 for maximum
  #maxDataMemoryMB: 100

  # Data location. Default is "$HOME/stores/server"
  #dataDir: "$HOME/stores/server"

  # names or paths to server TLS server certificate and key file
  # the default dir is "$HOME/certs"
  #serverCertFile: "serverCert.pem"
  #serverKeyFile: "serverKey.pem"

  # path to x509 CA certificate file that signed the server cert
  #caCertFile: "caCert.pem"
  #caKeyFile: "caKey.pem"

  # Name of application account. Default is hiveotapp
  #appAccountName: "hiveotapp"
  # name or path to the application account key file. The default dir is "$HOME/certs"
  #appAccountKeyFile: "hiveotAcct.nkey"

  # disable running the embedded messaging server
  #noAutoStart: true     # dont start the embedded server

# Authentication service configuration
authn:
  # name or path to password file, with stored bcrypted passwords
  # Default dir is "$HOME/stores/authn"
  # This contains sensitive information and should only be readable by the core process
  #passwordFile "hub.passwd"

  # optional override of the renewed auth token validity in days
  # for devices, services and users.
  #  0 for default; -1 for indefinitely
  #deviceTokenValidityDays: 90
  #serviceTokenValidityDays: 366
  #userTokenValidityDays: 30

  # Don't start the embedded authentication service
  # Use this for testing or when authn is running stand-alone
  #noAutoStart: true

# Authorization service configuration
authz:
  # directory to store groups. Default is $HOME/stores/authz
  # This contains sensitive information and should only be readable by the core process
  #groupsDir: "$HOME/stores/authz"

  # Do not auto-start the embedded authorization service
  # Use this for testing or when authz is running stand-alone
  #noAutoStart: true

