# hub.yaml contains the hiveot hub core configuration

# run the core using nats or mqtt (currently only nats)
#core: "nats"

# Alternative home directory. default is the parent of the application binary
#homeDir: ""

# filename of the x509 CA certificate file in the certs directory
#caCertFile: "caCert.pem"
#caKeyFile: "caKey.pem"

# names or paths to server TLS server certificate and key file
# the default dir is "$CERTS"
#serverCertFile: "serverCert.pem"
#serverKeyFile: "serverKey.pem"

# Nats Messaging server configuration
natsserver:
  # specific listening address, default is 127.0.0.1
  # the host name or IP must match that of the certificate for TLS to work
  #host: "127.0.0.1"

  # default listening TLS port is 4222 and 8222 for websocket
  #port: 4222
  #wsPort: 8222   # default disabled

  # logging level for server: debug, info, warn (default), error
  #logLevel: "warn"
  # logfile to write to in the logging folder. (default stderr)
  #logFile: "hubcore.log"
  # enable server debug output (default falseO0
  #debug: false

  # maximum in-memory RAM usage. Default (0) is 1024. -1 for maximum
  #maxDataMemoryMB: 1024

  # Data location. Default is "$Home/stores/natsserver"
  #dataDir: "$HOME/stores/natsserver"

  # Name of application account. Default is hiveot
  #appAccountName: "hiveot"
  # name or path to the application account key file. Default appAcct.nkey
  #appAccountKeyFile: "appAcct.nkey"
  #adminUserKeyFile: "admin.nkey"
  #systemUserKeyFile: "systemUser.nkey"

  # Disable running the embedded messaging server
  #noAutoStart: true     # dont start the embedded server

# Mqtt Messaging server configuration
mqttserver:
  # specific listening address, default is 127.0.0.1
  # the host name or IP must match that of the certificate for TLS to work
  #host: "127.0.0.1"

  # default listening TLS port is 4222 and 8222 for websocket
  #port: 8333
  #wsPort: 9001   # default disabled


# Authentication and authorization configuration
auth:
  # name or path to password file, with stored bcrypted passwords
  # default location is $HOME/stores/authn.
  # This contains sensitive information and should only be readable by the core process
  #passwordFile: "hub.passwd"

  # password hash format. argon2id or bcrypt. Nats requires bcrypt.
  #encryption: bcrypt

  # optional override of the renewed auth token validity in days
  # for devices, services and users.
  #  0 for default; -1 for indefinitely
  #deviceTokenValidityDays: 90
  #serviceTokenValidityDays: 366
  #userTokenValidityDays: 30

  # Don't start the embedded authentication service
  # Use this for testing or when authn is running stand-alone
  #noAutoStart: true

  # service roles to register which service capabilities are available to what roles
  # todo. this is currently hard coded