import {nanoid} from "nanoid";

// two hiveot message types to rule them all
export const MessageTypeRequest = "request"
export const MessageTypeResponse = "response"


// request status
// this aligns with action status values from WoT spec
// The request has not yet been delivered
export const StatusPending = "pending"

// The request is being processed
export const StatusRunning = "running"

// The request processing was completed
export const StatusCompleted = "completed"

// The request processing or delivery failed
export const StatusFailed = "failed"


// RequestMessage for sending a request for an operation on a Thing or service.
// Agents/Things MUST send a response when a request is received and a correlationID
// is included.
//
// The following operations are considered to be requests:
//
//   - invokeaction  [WoT]
//   - subscribe, unsubscribe [WoT]   (handled by protocol bindings)
//   - observe, unobserve [WoT]       (handled by protocol bindings)
//   - readproperty, readallproperties [WoT]
//   - queryaction, queryallactions [WoT]
//   - readevent, readallevents  (of a Thing)  [HiveOT extension]
//   - readtd, readalltds  (of a directory or thing) [HiveOT extension]
export class RequestMessage extends Object {
    //
    public constructor(init?:Partial<RequestMessage>) {
        super();
        this.messageID = nanoid()
        this.operation = ""
        Object.assign(this, init)
    }

    // public constructor(operation: string, thingID: string, name: string, input: any) {
    //     super()
    //     this.operation = operation
    //     this.thingID = thingID
    //     this.name = name
    //     this.input = input
    //     this.correlationID = nanoid()
    // }

    // MessageType identifies this message payload as a request
    // Intended to identify this message envelope.
    messageType: string = MessageTypeRequest

    // Message operation. Eg: WotOpInvokeAction, WotOpPublishEvent, ...
    // This is required.
    public operation: string

    // ThingID of the thing this request is for.
    // For messages from consumers this is the digitwin dThingID
    // For messages to agents this is the agent ThingID
    // This field is required.
    public thingID: string = ""

    // Name of the event, action or property affordance the request is for.
    // This field is optional and only required for specific operations.
    public name: string = ""

    // Input for the request as described in the TD affordance dataschema.
    // If the operation is one of the Thing level operations, the input is specified
    // by the operation's dataschema. WoT doesn't have this yet so hiveot will
    // define the missing bits if any.
    public input?: any

    // correlationID of the message. Uniquely identifies the request and must
    // be included in the response.
    // Notifications can include this to correlate with the subscription.
    // Message streams can include this to correlate with the original request.
    // This is optional. If omitted, no response will be received.
    public correlationID?: string

    //--- fields populated by the protocol transport

    // SenderID is the account ID of the client sending the request.
    // The protocol server MUST set this to the authenticated client.
    public senderID?: string

    // Created holds the timestamp the request was created using RFC3339milli
    // This MUST be set by the protocol server if not provided.
    public created?: string

    // MessageID unique ID of the message. Intended to detect duplicates.
    // Generated by the protocol binding.
    public messageID: string

    public createResponse(output: any, err?: Error): ResponseMessage {
        let resp = new ResponseMessage(
            this.operation, this.thingID, this.name, output, err?.message, this.correlationID)
        resp.received = this.created
        return resp
    }
}

// ResponseMessage serves to notify a single client of the result of a request.
// The operation of the response MUST be that of the request.
export class ResponseMessage extends Object {
    public constructor(op:string, thingID:string,name:string,output:any,
                       err?:string, correlationID?:string) {
        super()
        this.operation = op
        this.thingID = thingID
        this.name = name
        this.output = output
        this.error = err
        this.correlationID = correlationID
        this.messageID = nanoid()
        this.status = (err) ? StatusFailed : StatusCompleted
    }
    // MessageType identifies this message payload as a request
    // Intended to identify this message envelope.
    public messageType: string = MessageTypeResponse

    // Operation of the request this is the response to.
    // This is required.
    public operation: string

    // CorrelationID of the message. Provided by the request and must be included
    // in the response.
    // This is required. If omitted, the response will be ignored.
    public correlationID?:string

    // Status of the request processing: pending, running, completed or failed
    // If status is failed then Error holds the reason and Output possible details
    public status: string

    // Output for the request as described in the TD affordance dataschema.
    // If the operation is one of the Thing level operations, the output is specified
    // by the operation's dataschema. WoT doesn't have this yet so hiveot will
    // define the missing bits if any. (see documentation)
    public output?: any

    // error contains the short error description when status is failed.
    public error?: string

    // Timestamp the request was received by the thing agent
    public received?: string

    // Timestamp the status was updated in this response
    // This will be set by the Hub if not provided.
    // public updated?: string = new Date().toISOString()
    public updated?: string

    // SenderID is the account ID of the agent sending the response.
    // The protocol server MUST set this to the authenticated client.
    public senderID: string = ""


    //--- additional optional fields

    // ThingID of the thing this is a response from.
    // For responses passed to consumers this is the digitwin dThingID
    // For responses sent by agents this is the agent ThingID
    // This field is optional and intended to help debugging and logging.
    public thingID?: string

    // Name of the action or property affordance this is a response from.
    // This field is optional and intended to help debugging and logging.
    public name?: string

    // MessageID unique ID of the message. Intended to detect duplicates.
    // Generated by the protocol binding.
    public messageID: string
}