import {nanoid} from "nanoid";

// three hiveot message types to rule them all
export const MessageTypeNotification = "notification"
export const MessageTypeRequest = "request"
export const MessageTypeResponse = "response"


// request status
// this aligns with action status values from WoT spec
// The request has not yet been delivered
export const StatusPending = "pending"

// The request is being processed
export const StatusRunning = "running"

// The request processing was completed
export const StatusCompleted = "completed"

// The request processing or delivery failed
export const StatusFailed = "failed"

// NotificationMessage serves to notify subscribers of a change as identified by
// the operation, thingID and affordance name.
// The following operations are considered notifications:
// * property: HTOpUpdateProperty: Update of a property value, send by Thing agent
// * event: HTOpPublishEvent: notification of event to subscribers of the Thing
export class NotificationMessage extends Object {

    public constructor(op: string, thingID: string, name: string, data: any) {
        super()
        this.operation = op
        this.thingID = thingID
        this.name = name
        this.data = data
    }

    // MessageType identifies this message payload as a notification
    // Intended to identify this message envelope.
    public MessageType: string = MessageTypeNotification

    // WoT operation. Eg: WotOpInvokeAction, WotOpPublishEvent, ...
    // This is required.
    public operation: string = ""

    // ThingID or capabilityID of the thing itself
    // For notifications received by consumers this is the digitwin dThingID
    // For notifications sent by agents this is the agent ThingID
    // This field is required.
    public thingID: string = ""

    // Name of event, action or property as defined in the TD event/action map.
    // This field is optional and only required for specific notifications.
    public name: string = ""

    // Optional data in native format as defined by the TD affordance DataSchema
    public data: any

    // Created holds the date-time the notification was created. using RFC3339milli
    // This MUST be set by the protocol binding if not provided.
    // public created?: string = new Date().toISOString()
    public created?: string

    // Timestamp the value was created in unix time, msec since Epoch Jan 1st,1970 00:00 utc
    // public createdMSec: number = 0

    // AgentID contains the Agent ID that published the notification
    // The protocol server MUST set this to the authenticated client.
    public senderID: string = ""

    // optional correlationID to link notifications to requests (subscription, streams)
    public correlationID?: string

    // messageID is the optional ID of the message, intended to detect duplication
    // Generated by the protocol binding.
    public messageID?: string
}


// RequestMessage for sending a request for an operation on a Thing or service.
// Agents/Things MUST send a response when a request is received and a correlationID
// is included.
//
// The following operations are considered to be requests:
//
//   - invokeaction  [WoT]
//   - subscribe, unsubscribe [WoT]   (handled by protocol bindings)
//   - observe, unobserve [WoT]       (handled by protocol bindings)
//   - readproperty, readallproperties [WoT]
//   - queryaction, queryallactions [WoT]
//   - readevent, readallevents  (of a Thing)  [HiveOT extension]
//   - readtd, readalltds  (of a directory or thing) [HiveOT extension]
export class RequestMessage extends Object {
    //
    public constructor(init?:Partial<RequestMessage>) {
        super();
        this.correlationID = nanoid()
        Object.assign(this, init)
    }

    // public constructor(operation: string, thingID: string, name: string, input: any) {
    //     super()
    //     this.operation = operation
    //     this.thingID = thingID
    //     this.name = name
    //     this.input = input
    //     this.correlationID = nanoid()
    // }

    // MessageType identifies this message payload as a request
    // Intended to identify this message envelope.
    messageType: string = MessageTypeRequest

    // Message operation. Eg: WotOpInvokeAction, WotOpPublishEvent, ...
    // This is required.
    public operation: string = ""

    // ThingID of the thing this request is for.
    // For messages from consumers this is the digitwin dThingID
    // For messages to agents this is the agent ThingID
    // This field is required.
    public thingID: string = ""

    // Name of the event, action or property affordance the request is for.
    // This field is optional and only required for specific operations.
    public name: string = ""

    // Input for the request as described in the TD affordance dataschema.
    // If the operation is one of the Thing level operations, the input is specified
    // by the operation's dataschema. WoT doesn't have this yet so hiveot will
    // define the missing bits if any.
    public input?: any

    // correlationID of the message. Uniquely identifies the request and must
    // be included in the response.
    // It can also be used in notification to subscriptions and streams.
    // This is optional. If omitted, no response will be sent.
    public correlationID?: string

    // SenderID is the account ID of the client sending the request.
    // The protocol server MUST set this to the authenticated client.
    public senderID: string = ""

    // Created holds the timestamp the request was created using RFC3339milli
    // This MUST be set by the protocol binding if not provided.
    public created?: string

    // MessageID unique ID of the message. Intended to detect duplicates.
    // Generated by the protocol binding.
    public messageID: string | undefined

    public createResponse(output: any, err?: Error): ResponseMessage {
        let resp = new ResponseMessage(
            this.operation, this.thingID, this.name, output, err?.message, this.correlationID)
        resp.received = this.created
        return resp
    }
}

// ResponseMessage serves to notify a single client of the result of a request.
// The operation of the response MUST be that of the request.
export class ResponseMessage extends Object {
    public constructor(op:string, thingID:string,name:string,output:any,
                       err?:string, correlationID?:string) {
        super()
        this.operation = op
        this.thingID = thingID
        this.name = name
        this.output = output
        this.error = err
        this.correlationID = correlationID
    }
    // MessageType identifies this message payload as a request
    // Intended to identify this message envelope.
    public messageType: string = MessageTypeResponse

    // Operation of the request this is the response to.
    // This is required.
    public operation: string = ""

    // CorrelationID of the message. Provided by the request and must be included
    // in the response.
    // This is required. If omitted, the response will be ignored.
    public correlationID?:string = ""

    // Status of the request processing: pending, running, completed or failed
    // If status is failed then Error holds the reason and Output possible details
    public status: string = StatusCompleted

    // Output for the request as described in the TD affordance dataschema.
    // If the operation is one of the Thing level operations, the output is specified
    // by the operation's dataschema. WoT doesn't have this yet so hiveot will
    // define the missing bits if any. (see documentation)
    public output?: any

    // error contains the short error description when status is failed.
    public error?: string

    // Timestamp the request was received by the thing agent
    public received?: string

    // Timestamp the status was updated in this response
    // This will be set by the Hub if not provided.
    // public updated?: string = new Date().toISOString()
    public updated?: string

    // SenderID is the account ID of the agent sending the response.
    // The protocol server MUST set this to the authenticated client.
    public senderID: string = ""


    //--- additional optional fields

    // ThingID of the thing this is a response from.
    // For responses passed to consumers this is the digitwin dThingID
    // For responses sent by agents this is the agent ThingID
    // This field is optional and intended to help debugging and logging.
    public thingID: string|undefined

    // Name of the action or property affordance this is a response from.
    // This field is optional and intended to help debugging and logging.
    public name: string|undefined

    // MessageID unique ID of the message. Intended to detect duplicates.
    // Generated by the protocol binding.
    public messageID: string|undefined
}