// Package authz with types of service 'Admin' from agent 'authz'
// DO NOT EDIT. This file is auto generated by tm2go. Any changes will be overwritten.
// Intended for use by both service agents and consumer.
// Generated 18 Nov 2025 13:58 PST. 
package authz


//--- Constants ---

// AdminAgentID is the account ID of the agent managing the Thing.
const AdminAgentID = "authz"

// AdminServiceID is the thingID of the device/service as used by agents.
// Agents use this to publish events and subscribe to actions
const AdminServiceID = "Admin"

// AdminDThingID is the Digitwin thingID as used by consumers. Digitwin adds the dtw:{agent} prefix to the serviceID
// Consumers use this to publish actions and subscribe to events
const AdminDThingID = "dtw:authz:Admin"

// Property, Event and Action names
const (
    AdminActionGetClientRole = "getClientRole"
    AdminActionSetClientRole = "setClientRole"
)
//--- Argument and Response struct for action of Thing 'admin' ---

const AdminGetClientRoleMethod = "getClientRole"

const AdminSetClientRoleMethod = "setClientRole"

// AdminSetClientRoleArgs defines the arguments of the setClientRole function
// Set Client Role - Update the role of a consumer
type AdminSetClientRoleArgs struct {
    
    // ClientID with Client ID
    ClientID string `json:"clientID,omitempty"`
    
    // Role with Client Role
    Role ClientRole `json:"role,omitempty"`
}


// AdminTD contains the raw TD of this service for publication to the Hub
const AdminTD = `{"actions":{"getClientRole":{"@type":"hiveot:function","description":"Read the role of a client","title":"Get Client Role","idempotent":true,"input":{"title":"ClientID","description":"ID of the service, agent or consumer","readOnly":false,"type":"string"},"output":{"title":"Role","description":"Response with client role","readOnly":false,"type":"ClientRole"},"safe":true},"setClientRole":{"@type":"hiveot:function","description":"Update the role of a consumer","title":"Set Client Role","idempotent":true,"input":{"readOnly":false,"type":"object","properties":{"clientID":{"title":"Client ID","readOnly":false,"type":"string"},"role":{"title":"Client Role","readOnly":false,"type":"ClientRole"}}}}},"allow":["admin"],"@context":["https://www.w3.org/2022/wot/td/v1.1",{"hiveot":"https://www.hiveot.net/vocab/v0.1"}],"@type":"Service","created":"2024-06-04T17:00:00.000Z","description":"HiveOT runtime service for administration of roles and permissions","events":{},"id":"Admin","modified":"2024-06-04T17:00:00.000Z","properties":{},"security":null,"securityDefinitions":null,"title":"Authorization Administration Service","support":"https://www.github.com/hiveot/hub"}`