// Package authz with the agent request handler for using service 'Admin'
// This builds a service consumer that send a service request.
// DO NOT EDIT. This file is auto generated by tm2go. Any changes will be overwritten.
// Generated 18 Nov 2025 13:58 PST.
package authz

import "github.com/hiveot/hub/lib/consumer"

// AdminGetClientRole client method - Get Client Role.
// Read the role of a client
func AdminGetClientRole(hc *consumer.Consumer, clientID string) (role ClientRole, err error) {

	err = hc.Rpc("invokeaction", AdminDThingID, AdminGetClientRoleMethod, &clientID, &role)
	return
}

// AdminSetClientRole client method - Set Client Role.
// Update the role of a consumer
func AdminSetClientRole(hc *consumer.Consumer, clientID string, role ClientRole) (err error) {
	var args = AdminSetClientRoleArgs{clientID, role}
	err = hc.Rpc("invokeaction", AdminDThingID, AdminSetClientRoleMethod, &args, nil)
	return
}
