// Package authz with the agent request handler for using service 'User'
// This builds a service consumer that send a service request.
// DO NOT EDIT. This file is auto generated by tm2go. Any changes will be overwritten.
// Generated 18 Nov 2025 13:58 PST.
package authz

import "github.com/hiveot/hub/lib/consumer"

// UserSetPermissions client method - Set Permissions.
// Set the roles that can use a Thing or service
func UserSetPermissions(hc *consumer.Consumer, permissions ThingPermissions) (err error) {

	err = hc.Rpc("invokeaction", UserDThingID, UserSetPermissionsMethod, &permissions, nil)
	return
}
