// Package authz with types and interfaces for using this service with agent 'authz'
// DO NOT EDIT. This file is auto generated by tdd2api. Any changes will be overwritten.
// Generated 04 Sep 24 19:21 PDT.
package authz

import "errors"
import "github.com/hiveot/hub/lib/utils"
import "github.com/hiveot/hub/lib/hubclient"

// UserAgentID is the connection ID of the agent managing the Thing.
const UserAgentID = "authz"

// UserServiceID is the internal thingID of the device/service as used by agents.
// Agents use this to publish events and subscribe to actions
const UserServiceID = "user"

// UserDThingID is the Digitwin thingID as used by agents. Digitwin adds the dtw:{agent} prefix to the serviceID
// Consumers use this to publish actions and subscribe to events
const UserDThingID = "dtw:authz:user"

//--- Schema definitions of Thing 'dtw:authz:user' ---

// ThingPermissions defines a Thing Permissions data schema of the authz agent.
//
// This defines the roles that have permissions to access this thing
// Used by agents and services to set the roles that can invoke actions on a service.
// These permissions are default recommendations made by the service provider.
// The authz service can override these defaults with another configuration.
type ThingPermissions struct {

	// AgentID with Agent ID
	//
	// The agent granting the permissions.
	AgentID string `json:"agentID,omitempty"`

	// Allow with Roles
	//
	// Roles allowed access to a Thing
	Allow []string `json:"allow,omitempty"`

	// Deny with
	Deny []string `json:"deny,omitempty"`

	// ThingID with Thing ID
	//
	// ThingID of the service whose permissions are set.
	// This is the ThingID as send by the agent, without the digitwin prefix.
	ThingID string `json:"thingID,omitempty"`
}

//--- Argument and Response struct for action of Thing 'dtw:authz:user' ---

const UserSetPermissionsMethod = "setPermissions"

// UserSetPermissions client method - Set Permissions.
// Set the roles that can use a Thing or service
func UserSetPermissions(hc hubclient.IHubClient, permissions ThingPermissions) (err error) {

	err = hc.Rpc(UserDThingID, UserSetPermissionsMethod, &permissions, nil)
	return
}

// IUserService defines the interface of the 'User' service
//
// This defines a method for each of the actions in the TD.
type IUserService interface {

	// SetPermissions Set Permissions
	// Set the roles that can use a Thing or service
	SetPermissions(senderID string, permissions ThingPermissions) error
}

// NewUserHandler returns a server handler for Thing 'dtw:authz:user' actions.
//
// This unmarshalls the request payload into an args struct and passes it to the service
// that implements the corresponding interface method.
//
// This returns the marshalled response data or an error.
func NewUserHandler(svc IUserService) func(*hubclient.ThingMessage) hubclient.DeliveryStatus {
	return func(msg *hubclient.ThingMessage) (stat hubclient.DeliveryStatus) {
		var err error
		var resp interface{}
		var senderID = msg.SenderID
		switch msg.Key {
		case "setPermissions":
			var args ThingPermissions
			err = utils.DecodeAsObject(msg.Data, &args)
			if err == nil {
				err = svc.SetPermissions(senderID, args)
			} else {
				err = errors.New("bad function argument: " + err.Error())
			}
			break
		default:
			err = errors.New("Unknown Method '" + msg.Key + "' of service '" + msg.ThingID + "'")
			stat.Failed(msg, err)
		}
		stat.Completed(msg, resp, err)
		return stat
	}
}

// UserTD contains the raw TD of this service for publication to the Hub
const UserTD = `{"@context":["https://www.w3.org/2022/wot/td/v1.1",{"ht":"https://www.hiveot.net/vocab/v0.1"}],"@type":"Service","created":"2024-06-04T17:00:00.000Z","description":"HiveOT runtime service for services setting permissions","id":"user","modified":"2024-06-04T17:00:00.000Z","support":"https://www.github.com/hiveot/hub","title":"Authorization Client Services","schemaDefinitions":{"ThingPermissions":{"title":"Thing Permissions","description":"This defines the roles that have permissions to access this thing","comments":["Used by agents and services to set the roles that can invoke actions on a service.","These permissions are default recommendations made by the service provider.","The authz service can override these defaults with another configuration."],"readOnly":false,"type":"object","properties":{"agentID":{"title":"Agent ID","description":"The agent granting the permissions.","readOnly":false,"type":"string"},"allow":{"title":"Roles","description":"Roles allowed access to a Thing","readOnly":false,"type":"array","items":{"title":"Role","description":"Role allowed access to a Thing","readOnly":false,"type":"string"}},"deny":{"readOnly":false,"type":"array","items":{"title":"Role","description":"Role denied access to the Thing","readOnly":false,"type":"string"}},"thingID":{"title":"Thing ID","description":"ThingID of the service whose permissions are set.","comments":["This is the ThingID as send by the agent, without the digitwin prefix."],"readOnly":false,"type":"string"}}}},"actions":{"setPermissions":{"@type":"ht:function","title":"Set Permissions","description":"Set the roles that can use a Thing or service","input":{"title":"Permissions","readOnly":false,"type":"ThingPermissions"},"idempotent":true}},"security":["bearer"],"securityDefinitions":{"bearer":{"scheme":""}}}`
