// Package authn with the agent request handler for using service 'Admin'
// This builds a service consumer that send a service request.
// DO NOT EDIT. This file is auto generated by tm2go. Any changes will be overwritten.
// Generated 18 Nov 2025 13:58 PST.
package authn

import "github.com/hiveot/hivekit/go/lib/consumer"

// AdminAddAgent client method - Add Agent.
// Create an account for IoT device agents
func AdminAddAgent(hc *consumer.Consumer, clientID string, displayName string, pubKey string) (token string, err error) {
	var args = AdminAddAgentArgs{clientID, displayName, pubKey}
	err = hc.Rpc("invokeaction", AdminDThingID, AdminAddAgentMethod, &args, &token)
	return
}

// AdminAddConsumer client method - Add Consumer.
// Add an end-user client
func AdminAddConsumer(hc *consumer.Consumer, clientID string, displayName string, password string) (err error) {
	var args = AdminAddConsumerArgs{clientID, displayName, password}
	err = hc.Rpc("invokeaction", AdminDThingID, AdminAddConsumerMethod, &args, nil)
	return
}

// AdminAddService client method - Add Service.
// Add a service account
func AdminAddService(hc *consumer.Consumer, clientID string, displayName string, pubKey string) (token string, err error) {
	var args = AdminAddServiceArgs{clientID, displayName, pubKey}
	err = hc.Rpc("invokeaction", AdminDThingID, AdminAddServiceMethod, &args, &token)
	return
}

// AdminGetClientProfile client method - Get Client Profile.
// Get the profile information describing a client
func AdminGetClientProfile(hc *consumer.Consumer, clientID string) (profile ClientProfile, err error) {

	err = hc.Rpc("invokeaction", AdminDThingID, AdminGetClientProfileMethod, &clientID, &profile)
	return
}

// AdminGetProfiles client method - Get Profiles.
// Get a list of all client profiles
func AdminGetProfiles(hc *consumer.Consumer) (clientProfiles []ClientProfile, err error) {

	err = hc.Rpc("invokeaction", AdminDThingID, AdminGetProfilesMethod, nil, &clientProfiles)
	return
}

// AdminGetSessions client method - Get Sessions.
// Get a list of active sessions
func AdminGetSessions(hc *consumer.Consumer) (clientSessions AdminGetSessionsResp, err error) {

	err = hc.Rpc("invokeaction", AdminDThingID, AdminGetSessionsMethod, nil, &clientSessions)
	return
}

// AdminNewAgentToken client method - New Agent Token.
// Obtain a new authentication token for an agent or service
func AdminNewAgentToken(hc *consumer.Consumer, agentID string) (token string, err error) {

	err = hc.Rpc("invokeaction", AdminDThingID, AdminNewAgentTokenMethod, &agentID, &token)
	return
}

// AdminRemoveClient client method - Remove Client.
// Remove a client account
func AdminRemoveClient(hc *consumer.Consumer, clientID string) (err error) {

	err = hc.Rpc("invokeaction", AdminDThingID, AdminRemoveClientMethod, &clientID, nil)
	return
}

// AdminSetClientPassword client method - Set Client Password.
// Update the password of a consumer
func AdminSetClientPassword(hc *consumer.Consumer, clientID string, password string) (err error) {
	var args = AdminSetClientPasswordArgs{clientID, password}
	err = hc.Rpc("invokeaction", AdminDThingID, AdminSetClientPasswordMethod, &args, nil)
	return
}

// AdminUpdateClientProfile client method - Update Client Profile.
// Update the details of a client
func AdminUpdateClientProfile(hc *consumer.Consumer, clientProfile ClientProfile) (err error) {

	err = hc.Rpc("invokeaction", AdminDThingID, AdminUpdateClientProfileMethod, &clientProfile, nil)
	return
}
