// Package authn with the agent request handler for using service 'User'
// This builds a service consumer that send a service request.
// DO NOT EDIT. This file is auto generated by tm2go. Any changes will be overwritten.
// Generated 18 Nov 2025 13:58 PST.
package authn

import "github.com/hiveot/hivekit/go/lib/consumer"

// UserGetProfile client method - Get Client Profile.
func UserGetProfile(hc *consumer.Consumer) (resp ClientProfile, err error) {

	err = hc.Rpc("invokeaction", UserDThingID, UserGetProfileMethod, nil, &resp)
	return
}

// UserLogin client method - Login.
// Login with password
func UserLogin(hc *consumer.Consumer, clientID string, password string) (token string, err error) {
	var args = UserLoginArgs{clientID, password}
	err = hc.Rpc("invokeaction", UserDThingID, UserLoginMethod, &args, &token)
	return
}

// UserLogout client method - Logout.
// Logout from all devices
func UserLogout(hc *consumer.Consumer) (err error) {

	err = hc.Rpc("invokeaction", UserDThingID, UserLogoutMethod, nil, nil)
	return
}

// UserRefreshToken client method - Request a new auth token for the current client.
func UserRefreshToken(hc *consumer.Consumer, oldToken string) (newToken string, err error) {

	err = hc.Rpc("invokeaction", UserDThingID, UserRefreshTokenMethod, &oldToken, &newToken)
	return
}

// UserUpdateName client method - Request changing the display name of the current client.
func UserUpdateName(hc *consumer.Consumer, newName string) (err error) {

	err = hc.Rpc("invokeaction", UserDThingID, UserUpdateNameMethod, &newName, nil)
	return
}

// UserUpdatePassword client method - Update Password.
// Request changing the password of the current client
func UserUpdatePassword(hc *consumer.Consumer, password string) (err error) {

	err = hc.Rpc("invokeaction", UserDThingID, UserUpdatePasswordMethod, &password, nil)
	return
}

// UserUpdatePubKey client method - Update Public Key.
// Request changing the public key on file of the current client.
func UserUpdatePubKey(hc *consumer.Consumer, publicKeyPEM string) (err error) {

	err = hc.Rpc("invokeaction", UserDThingID, UserUpdatePubKeyMethod, &publicKeyPEM, nil)
	return
}
