# zwavejs binding configuration file

# Binding ID used for publications. 
# Multiple instances must use different IDs. 
#loginID: zwavejs
#loginToken: {credentials}

# Gateway connection protocol, address, port. Default is automatic
#hubURL: mqtts://localhost:8883

# Optionally write discovered value ID's to a csv file. Intended for troubleshooting.
#vidCsvFile: /home/henk/bin/hiveot/logs/zwinfo.csv

# ZWave S2 security keys. 16 Byte hex strings
# Keep these secure to protect your network:
S2_Unauthenticated: 00112233445566778899aabbccddeeff
S2_Authenticated: 00112233445566778899aabbccddeeff
S2_AccessControl: 00112233445566778899aabbccddeeff
S2_Legacy: 00112233445566778899aabbccddeeff


# Serial port of ZWave USB controller. Default is automatic.
#zwPort: /dev/ttyACM0
#zwPort: /dev/serial/by-id/usb-0658_0200-if00

# Disable zwavejs soft reset on startup when the controller doesn't support soft reset.
#zwDisableSoftReset: false

# Optional logging of zwavejs driver
# error, warn (default), http, info, verbose, or debug
#zwLogFile: /home/henk/bin/hiveot/logs/zwavejs-driver.log
#zwLogLevel: warn

# Location where the ZWavejs driver stores its data
# defaults is in {home}/stores/{clientID}
#storesDir: /home/henk/bin/hiveot/stores/zwavejs

# maximum number of scenes, to reduce TD document size. Default is 10
#maxNrScenes: 10

# publish only changed values on update (default true)
#publishOnlyChanges: true

# bindling loglevel: error, warn (default), info, debug. 
#loglevel: info

