package plugin

import (
	"log/slog"
	"os"

	"github.com/hiveot/hivekit/go/agent"
	"github.com/hiveot/hivekit/go/client"
)

type PluginConfig struct {
	LogLevel string `yaml:""`
}

// IPlugin interface of protocol bindings and service plugins
type IPlugin interface {
	// Start the plugin with the given environment settings and hub connection
	//	ag is the agent with the capability for publishing and subscribing
	Start(ag *agent.Agent) error
	Stop()
}

// StartPlugin implements the boilerplate to launch a plugin based on argv
// and its config. This does not return until a signal is received.
//
// This creates a connection to HiveOT Hub using the clientID and corresponding
// auth token from the certs directory.
//
// The auth token is generated by the launcher or can be provided out-of-band
// using the hub cli and copying it into the certs directory.
//
// AppEnvironment sets the plugin clientID to the application executable name. It can
// be changed by setting env.SenderID before invoking StartPlugin.
// The plugin clientID is used to connect to the hub and lookup a keys and token files
// with the same name in the env.CertsDir directory.
//
//	plugin is the instance of the plugin with Start and Stop methods.
//	clientID is the client's connect ID. certsDir is the location with the service token
//	 file, primary key, and CA certificate.
//	certDir contains the service auth tokens
//	serverURL is the URL of the hub server to connect to, if provided
func StartPlugin(plugin IPlugin, clientID string, certsDir string, serverURL string) {

	cc, token, _, err := client.ConnectWithTokenFile(clientID, certsDir, serverURL, 0)
	_ = token

	if err != nil {
		slog.Error("Failed connecting to the Hub", "err", err)
		os.Exit(1)
	}
	// start the service with the agent.
	ag := agent.NewAgent(cc, nil, nil, nil, nil, 0)
	err = plugin.Start(ag)
	if err != nil {
		slog.Error("failed starting service", "err", err.Error())
		os.Exit(1)
	}
	WaitForSignal()
	plugin.Stop()

	os.Exit(0)

}
