package plugin

import (
	"log/slog"
	"os"
	"path"

	"github.com/hiveot/hivekit/go/modules"
	"github.com/hiveot/hivekit/go/modules/factory"
	"github.com/hiveot/hivekit/go/modules/transport"
	"github.com/hiveot/hivekit/go/modules/transport/clients"
	"github.com/hiveot/hivekit/go/utils"
)

// StartPlugin implements the boilerplate to launch a plugin based on argv
// and its config. This does not return until a signal is received.
//
// This creates a connection to HiveOT Hub using the clientID and corresponding
// auth token from the certs directory.
//
// The auth token is generated by the launcher or can be provided out-of-band
// using the hub cli and copying it into the certs directory.
//
// AppEnvironment sets the plugin clientID to the application executable name. It can
// be changed by setting env.SenderID before invoking StartPlugin.
// The plugin clientID is used to connect to the hub and lookup a keys and token files
// with the same name in the env.CertsDir directory.
//
//	plugin is the instance of the plugin with Start and Stop methods.
//	clientID is the client's connect ID. certsDir is the location with the service token
//	 file, primary key, and CA certificate.
//	certDir contains the service auth tokens
//	serverURL is the URL of the hub server to connect to, if provided
func StartPlugin(plugin modules.IHiveModule, clientID string, certsDir string, serverURL string) {

	// temporary locate home as the parten of certs
	homeDir := path.Dir(certsDir)
	env := factory.NewAppEnvironment(homeDir, true)
	cc, err := clients.NewTransportClient(
		transport.ProtocolTypeWotWebsocket, serverURL, env.CaCert)

	token := env.GetAppToken()
	cc.AuthenticateWithToken(clientID, token)
	cc.Connect()
	// cc, token, _, err := clients.ConnectWithTokenFile(clientID, certsDir, serverURL, 0)
	_ = token

	if err != nil {
		slog.Error("Failed connecting to the Hub", "err", err)
		os.Exit(1)
	}
	// start the service with the agent.
	// ag := agent.NewAgent(cc, nil, nil, nil, nil, 0)
	err = plugin.Start()
	if err != nil {
		slog.Error("failed starting service", "err", err.Error())
		os.Exit(1)
	}
	utils.WaitForSignal()
	plugin.Stop()

	os.Exit(0)
}
