// Package digitwin with types and interfaces for using this service with agent 'digitwin'
// DO NOT EDIT. This file is auto generated by tdd2api. Any changes will be overwritten.
// Generated 30 Jun 24 23:10 PDT.
package digitwin

import "errors"
import "github.com/hiveot/hub/lib/things"
import "github.com/hiveot/hub/lib/hubclient"

// OutboxAgentID is the connection ID of the agent managing the Thing.
const OutboxAgentID = "digitwin"

// OutboxServiceID is the internal thingID of the device/service as used by agents.
// Agents use this to publish events and subscribe to actions
const OutboxServiceID = "outbox"

// OutboxDThingID is the Digitwin thingID as used by agents. Digitwin adds the dtw:{agent} prefix to the serviceID
// Consumers use this to publish actions and subscribe to events
const OutboxDThingID = "dtw:digitwin:outbox"

//--- Argument and Response struct for action of Thing 'dtw:digitwin:outbox' ---

const OutboxReadLatestMethod = "readLatest"

// OutboxReadLatestArgs defines the arguments of the readLatest function
// Read Latest - Read the latest value(s) of a Thing
type OutboxReadLatestArgs struct {

	// Keys with Value Key
	//
	// The event/property IDs to read or empty to read all latest values
	Keys []string `json:"keys,omitempty"`

	// Since with Since
	//
	// Only return values updated since
	Since string `json:"since,omitempty"`

	// ThingID with Thing ID
	//
	// ID of the Thing to read
	ThingID string `json:"thingID,omitempty"`
}

// OutboxReadLatestResp defines the response of the readLatest function
// Read Latest - Read the latest value(s) of a Thing
//
// JSON encoded map of key:ThingMessage objects
type OutboxReadLatestResp struct {

	// Output with Value map
	//
	// JSON encoded map of key:ThingMessage objects
	Output map[string]interface{} `json:"output,omitempty"`
}

const OutboxRemoveValueMethod = "removeValue"

// OutboxReadLatest client method - Read Latest.
// Read the latest value(s) of a Thing
func OutboxReadLatest(hc hubclient.IHubClient, keys []string, since string, thingID string) (valuemap map[string]interface{}, err error) {
	var args = OutboxReadLatestArgs{keys, since, thingID}
	err = hc.Rpc(OutboxDThingID, OutboxReadLatestMethod, &args, &valuemap)
	return
}

// OutboxRemoveValue client method - Remove Thing Value.
// Remove a value
func OutboxRemoveValue(hc hubclient.IHubClient, messageID string) (err error) {

	err = hc.Rpc(OutboxDThingID, OutboxRemoveValueMethod, &messageID, nil)
	return
}

// IOutboxService defines the interface of the 'Outbox' service
//
// This defines a method for each of the actions in the TD.
type IOutboxService interface {

	// ReadLatest Read Latest
	// Read the latest value(s) of a Thing
	// This returns a jSON encoded map of key:ThingMessage objects
	ReadLatest(senderID string, args OutboxReadLatestArgs) (valuemap map[string]interface{}, err error)

	// RemoveValue Remove Thing Value
	// Remove a value
	RemoveValue(senderID string, messageID string) error
}

// NewOutboxHandler returns a server handler for Thing 'dtw:digitwin:outbox' actions.
//
// This unmarshalls the request payload into an args struct and passes it to the service
// that implements the corresponding interface method.
//
// This returns the marshalled response data or an error.
func NewOutboxHandler(svc IOutboxService) func(*things.ThingMessage) hubclient.DeliveryStatus {
	return func(msg *things.ThingMessage) (stat hubclient.DeliveryStatus) {
		var err error
		var resp interface{}
		var senderID = msg.SenderID
		switch msg.Key {
		case "readLatest":
			args := OutboxReadLatestArgs{}
			err = msg.Decode(&args)
			if err == nil {
				resp, err = svc.ReadLatest(senderID, args)
			} else {
				err = errors.New("bad function argument: " + err.Error())
			}
			break
		case "removeValue":
			var args string
			err = msg.Decode(&args)
			if err == nil {
				err = svc.RemoveValue(senderID, args)
			} else {
				err = errors.New("bad function argument: " + err.Error())
			}
			break
		default:
			err = errors.New("Unknown Method '" + msg.Key + "' of service '" + msg.ThingID + "'")
			stat.Failed(msg, err)
		}
		if resp != nil {
			stat.MarshalReply(resp)
		}
		stat.Completed(msg, err)
		return stat
	}
}
