// Package authn with types and interfaces for using this service with agent 'authn'
// DO NOT EDIT. This file is auto generated by tdd2api. Any changes will be overwritten.
// Generated 08 Jun 24 22:25 PDT.
package authn

import "encoding/json"
import "errors"
import "github.com/hiveot/hub/lib/things"
import "github.com/hiveot/hub/lib/hubclient"

// AdminAgentID is the connection ID of the agent managing the Thing.
const AdminAgentID = "authn"

// AdminServiceID is the internal thingID of the device/service as used by agents.
// Agents use this to publish events and subscribe to actions
const AdminServiceID = "admin"

// AdminDThingID is the Digitwin thingID as used by agents. Digitwin adds the dtw:{agent} prefix to the serviceID
// Consumers use this to publish actions and subscribe to events
const AdminDThingID = "dtw:authn:admin"

//--- Argument and Response struct for action of Thing 'dtw:authn:admin' ---

const AdminAddAgentMethod = "addAgent"

// AdminAddAgentArgs defines the arguments of the addAgent function
// Add Agent - Create an account for IoT device agents
type AdminAddAgentArgs struct {

	// ClientID with Client ID
	ClientID string `json:"clientID,omitempty"`

	// DisplayName with Display Name
	DisplayName string `json:"displayName,omitempty"`

	// PubKey with Public Key
	PubKey string `json:"pubKey,omitempty"`
}

const AdminAddConsumerMethod = "addConsumer"

// AdminAddConsumerArgs defines the arguments of the addConsumer function
// Add Consumer - Add an end-user client
type AdminAddConsumerArgs struct {

	// ClientID with Client ID
	ClientID string `json:"clientID,omitempty"`

	// DisplayName with Display Name
	DisplayName string `json:"displayName,omitempty"`

	// Password with Password
	Password string `json:"password,omitempty"`
}

const AdminAddServiceMethod = "addService"

// AdminAddServiceArgs defines the arguments of the addService function
// Add Service - Add a service account
type AdminAddServiceArgs struct {

	// ClientID with Client ID
	ClientID string `json:"clientID,omitempty"`

	// DisplayName with Display Name
	DisplayName string `json:"displayName,omitempty"`

	// PubKey with Public Key
	PubKey string `json:"pubKey,omitempty"`
}

const AdminGetClientProfileMethod = "getClientProfile"

const AdminGetProfilesMethod = "getProfiles"

const AdminNewAuthTokenMethod = "newAuthToken"

const AdminRemoveClientMethod = "removeClient"

const AdminSetClientPasswordMethod = "setClientPassword"

// AdminSetClientPasswordArgs defines the arguments of the setClientPassword function
// Set Client Password - Update the password of a consumer
//
// Client ID and password
type AdminSetClientPasswordArgs struct {

	// ClientID with Client ID
	ClientID string `json:"clientID,omitempty"`

	// Password with Password
	Password string `json:"password,omitempty"`
}

const AdminUpdateClientProfileMethod = "updateClientProfile"

// AdminClient client for talking to the 'dtw:authn:admin' service
type AdminClient struct {
	dThingID string
	hc       hubclient.IHubClient
}

// AddAgent client method - Add Agent.
// Create an account for IoT device agents
func (svc *AdminClient) AddAgent(agentInfo AdminAddAgentArgs) (token string, err error) {
	err = svc.hc.Rpc(svc.dThingID, AdminAddAgentMethod, &agentInfo, &token)
	return
}

// AddConsumer client method - Add Consumer.
// Add an end-user client
func (svc *AdminClient) AddConsumer(consumerInfo AdminAddConsumerArgs) (err error) {
	err = svc.hc.Rpc(svc.dThingID, AdminAddConsumerMethod, &consumerInfo, nil)
	return
}

// AddService client method - Add Service.
// Add a service account
func (svc *AdminClient) AddService(serviceInfo AdminAddServiceArgs) (token string, err error) {
	err = svc.hc.Rpc(svc.dThingID, AdminAddServiceMethod, &serviceInfo, &token)
	return
}

// GetClientProfile client method - Get Client Profile.
// Get the profile information describing a client
func (svc *AdminClient) GetClientProfile(clientID string) (profile ClientProfile, err error) {
	err = svc.hc.Rpc(svc.dThingID, AdminGetClientProfileMethod, &clientID, &profile)
	return
}

// GetProfiles client method - Get Profiles.
// Get a list of all client profiles
func (svc *AdminClient) GetProfiles() (clientProfiles []ClientProfile, err error) {
	err = svc.hc.Rpc(svc.dThingID, AdminGetProfilesMethod, nil, &clientProfiles)
	return
}

// NewAuthToken client method - New Authentication Token.
// Obtain a new authentication token for an agent or service
func (svc *AdminClient) NewAuthToken(clientID string) (token string, err error) {
	err = svc.hc.Rpc(svc.dThingID, AdminNewAuthTokenMethod, &clientID, &token)
	return
}

// RemoveClient client method - Remove Client.
// Remove a client account
func (svc *AdminClient) RemoveClient(clientID string) (err error) {
	err = svc.hc.Rpc(svc.dThingID, AdminRemoveClientMethod, &clientID, nil)
	return
}

// SetClientPassword client method - Set Client Password.
// Update the password of a consumer
func (svc *AdminClient) SetClientPassword(clientInfo AdminSetClientPasswordArgs) (err error) {
	err = svc.hc.Rpc(svc.dThingID, AdminSetClientPasswordMethod, &clientInfo, nil)
	return
}

// UpdateClientProfile client method - Update Client Profile.
// Update the details of a client
func (svc *AdminClient) UpdateClientProfile(clientProfile ClientProfile) (err error) {
	err = svc.hc.Rpc(svc.dThingID, AdminUpdateClientProfileMethod, &clientProfile, nil)
	return
}

// NewAdminClient creates a new client for invoking Authentication Administration Service methods.
func NewAdminClient(hc hubclient.IHubClient) *AdminClient {
	cl := AdminClient{
		hc:       hc,
		dThingID: "dtw:authn:admin",
	}
	return &cl
}

// IAdminService defines the interface of the 'Admin' service
//
// This defines a method for each of the actions in the TD.
type IAdminService interface {

	// AddAgent Add Agent
	// Create an account for IoT device agents
	// This returns a agent authentication token
	AddAgent(senderID string, agentInfo AdminAddAgentArgs) (token string, err error)

	// AddConsumer Add Consumer
	// Add an end-user client
	AddConsumer(senderID string, consumerInfo AdminAddConsumerArgs) error

	// AddService Add Service
	// Add a service account
	// This returns a service authentication token
	AddService(senderID string, serviceInfo AdminAddServiceArgs) (token string, err error)

	// GetClientProfile Get Client Profile
	// Get the profile information describing a client
	GetClientProfile(senderID string, clientID string) (profile ClientProfile, err error)

	// GetProfiles Get Profiles
	// Get a list of all client profiles
	GetProfiles(senderID string) (clientProfiles []ClientProfile, err error)

	// NewAuthToken New Authentication Token
	// Obtain a new authentication token for an agent or service
	// This returns a new service or agent authentication token
	NewAuthToken(senderID string, clientID string) (token string, err error)

	// RemoveClient Remove Client
	// Remove a client account
	RemoveClient(senderID string, clientID string) error

	// SetClientPassword Set Client Password
	// Update the password of a consumer
	SetClientPassword(senderID string, clientInfo AdminSetClientPasswordArgs) error

	// UpdateClientProfile Update Client Profile
	// Update the details of a client
	UpdateClientProfile(senderID string, clientProfile ClientProfile) error
}

// NewAdminHandler returns a server handler for Thing 'dtw:authn:admin' actions.
//
// This unmarshalls the request payload into an args struct and passes it to the service
// that implements the corresponding interface method.
//
// This returns the marshalled response data or an error.
func NewAdminHandler(svc IAdminService) func(*things.ThingMessage) hubclient.DeliveryStatus {
	return func(msg *things.ThingMessage) (stat hubclient.DeliveryStatus) {
		var err error
		var resp interface{}
		var senderID = msg.SenderID
		switch msg.Key {
		case "addAgent":
			args := AdminAddAgentArgs{}
			err = msg.Unmarshal(&args)
			if err == nil {
				resp, err = svc.AddAgent(senderID, args)
			} else {
				err = errors.New("bad function argument: " + err.Error())
			}
			break
		case "addConsumer":
			args := AdminAddConsumerArgs{}
			err = msg.Unmarshal(&args)
			if err == nil {
				err = svc.AddConsumer(senderID, args)
			} else {
				err = errors.New("bad function argument: " + err.Error())
			}
			break
		case "addService":
			args := AdminAddServiceArgs{}
			err = msg.Unmarshal(&args)
			if err == nil {
				resp, err = svc.AddService(senderID, args)
			} else {
				err = errors.New("bad function argument: " + err.Error())
			}
			break
		case "getProfiles":
			if err == nil {
				resp, err = svc.GetProfiles(senderID)
			} else {
				err = errors.New("bad function argument: " + err.Error())
			}
			break
		case "newAuthToken":
			var args string
			err = msg.Unmarshal(&args)
			if err == nil {
				resp, err = svc.NewAuthToken(senderID, args)
			} else {
				err = errors.New("bad function argument: " + err.Error())
			}
			break
		case "removeClient":
			var args string
			err = msg.Unmarshal(&args)
			if err == nil {
				err = svc.RemoveClient(senderID, args)
			} else {
				err = errors.New("bad function argument: " + err.Error())
			}
			break
		case "getClientProfile":
			var args string
			err = msg.Unmarshal(&args)
			if err == nil {
				resp, err = svc.GetClientProfile(senderID, args)
			} else {
				err = errors.New("bad function argument: " + err.Error())
			}
			break
		case "setClientPassword":
			args := AdminSetClientPasswordArgs{}
			err = msg.Unmarshal(&args)
			if err == nil {
				err = svc.SetClientPassword(senderID, args)
			} else {
				err = errors.New("bad function argument: " + err.Error())
			}
			break
		case "updateClientProfile":
			var args ClientProfile
			err = msg.Unmarshal(&args)
			if err == nil {
				err = svc.UpdateClientProfile(senderID, args)
			} else {
				err = errors.New("bad function argument: " + err.Error())
			}
			break
		default:
			err = errors.New("Unknown Method '" + msg.Key + "' of service '" + msg.ThingID + "'")
			stat.Failed(msg, err)
		}
		if resp != nil {
			stat.Reply, _ = json.Marshal(resp)
		}
		stat.Completed(msg, err)
		return stat
	}
}
