package genagent

import (
	"time"

	"github.com/hiveot/hivekit/go/wot/td"
	"github.com/hiveot/hub/cmd/tm2go/gentypes"
)

// GenAgent is the main function to generate the agent request handler that
// maps requests to service calls and returns the service result.
func GenAgent(l *gentypes.SL, agentID string, tdi *td.TD) (err error) {

	serviceID := gentypes.ToTitle(tdi.ID)

	genImports(l, agentID, serviceID)
	GenServiceInterface(l, agentID, serviceID, tdi)
	GenServiceAgent(l, agentID, serviceID, tdi)
	return nil
}

// imports needed for the agent
func genImports(l *gentypes.SL, agentID string, serviceID string) {

	l.Add("// Package %s with the agent request handler for using service '%s'",
		agentID, serviceID)
	l.Add("// This builds a service agent that calls the service.")
	l.Add("// DO NOT EDIT. This file is auto generated by tm2go. Any changes will be overwritten.")
	l.Add("// Generated %s. ", time.Now().Format("02 Jan 2006 15:04 MST"))
	l.Add("package %s", agentID)

	l.Add("")
	l.Add("import \"errors\"")
	//l.Add("import \"github.com/hiveot/hub/lib/messaging/messaging\"")
	l.Add("import \"github.com/hiveot/hivekit/go/utils\"")
	l.Add("import \"github.com/hiveot/hub/lib/messaging\"")
	l.Add("")
}
